project:
  type: website
  output-dir: docs

website:
  title: "NLP Blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/snagjincha/NLP

format:
  html:
    theme: cosmo
    number-sections: false
    toc: true
    toc-location: right
    highlight-style: github
    toc-depth: 2
